# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="jraqula"
DEFAULT_USER=`whoami`
COMPLETION_WAITING_DOTS="true"

plugins=(git)
fpath=( ~/.eden/functions "${fpath[@]}" )

source $ZSH/oh-my-zsh.sh
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

ls -d1 $HOME/.eden/sources/* | while read document
do
  source $document
done

ls -1 $HOME/.eden/functions | while read filename
do
  autoload -Uz $filename
done

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
