dofile("./window_management/geometry.lua")
dofile("./window_management/tray.lua")
dofile("./window_management/max.lua")
dofile("./window_management/screens.lua")
dofile("./window_management/cursor.lua")

hs.hotkey.bind({"cmd", "alt", "ctrl"}, "0", tray_0)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "M", rmain)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "1", tray_1)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "2", tray_2)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "3", tray_3)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "4", tray_4)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "5", tray_5)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "Left", rleft)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "Right", rright)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "Up", rtop)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "Down", rbottom)

hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "M", max_M)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "0", max_0)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "1", max_1)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "2", max_2)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "3", max_3)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "4", max_4)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "5", max_5)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "Left", max_L)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "Right", max_R)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "Up", max_UP)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "Down", max_DN)

hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "]", moveToNext)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "[", moveToPrev)

hs.hotkey.bind({"cmd", "alt", "ctrl"}, "G", centerCursor)

ms = require('mostly_sane/ms')
ms.mute_on_wake.enable()
ms.bluetooth.enable()
ms.dim_on_wake.enable()
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "B", ms.bluetooth.toggle_command)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "Z", ms.sleep_hotkey.sleep)
hs.hotkey.bind({"shift"}, "space", ms.simple_space.tapSpace)

bc = require('better_content/bc')
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "V", bc.pasteboard.typeKeys)
