dofile("./window_management/geometry.lua")
dofile("./window_management/tray.lua")
dofile("./window_management/max.lua")
dofile("./window_management/screens.lua")
dofile("./window_management/cursor.lua")

hs.hotkey.bind({"cmd", "alt", "ctrl"}, "0", rzero)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "M", rmain)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "1", rone)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "2", rtwo)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "3", rthree)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "4", rfour)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "Left", rleft)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "Right", rright)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "Up", rtop)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "Down", rbottom)

hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "M", xmain)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "1", xone)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "2", xtwo)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "3", xthree)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "4", xfour)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "Left", xleft)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "Right", xright)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "Up", xtop)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "Down", xbottom)

hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "]", moveToNext)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "[", moveToPrev)

hs.hotkey.bind({"cmd", "alt", "ctrl"}, "G", centerCursor)

ms = require('mostly_sane/ms')
ms.mute_on_wake.enable()
ms.bluetooth.enable()
ms.dim_on_wake.enable()
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "B", ms.bluetooth.toggle_command)

bc = require('better_content/bc')
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "V", bc.pasteboard.typeKeys)
