dofile("./window_management/geometry.lua")
dofile("./window_management/tray.lua")
dofile("./window_management/max.lua")

hs.hotkey.bind({"cmd", "alt", "ctrl"}, "0", rzero)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "M", rmain)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "1", rone)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "2", rtwo)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "3", rthree)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "4", rfour)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "Left", rleft)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "Right", rright)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "Up", rtop)
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "Down", rbottom)

hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "M", xmain)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "1", xone)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "2", xtwo)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "3", xthree)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "4", xfour)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "Left", xleft)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "Right", xright)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "Up", xtop)
hs.hotkey.bind({"cmd", "alt", "ctrl", "shift"}, "Down", xbottom)

ms = require('mostly_sane/mute_on_wake')
ms.mute_on_wake()
